apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-staging
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 82
